'use strict';

/**
 * Credential reader for E2E tests.
 *
 * Reads credentials generated by globalSetup.js (which runs
 * the generate-e2e-credentials script as a separate Node process).
 * This file intentionally has NO dependency on the opentok package
 * to avoid ESM compatibility issues in the Jest/Detox environment.
 */

const fs = require('fs');
const path = require('path');

const CREDENTIALS_PATH = path.join(__dirname, '../.e2e-credentials.json');

/**
 * Reads the generated credentials file.
 * Throws with clear instructions if the file doesn't exist.
 *
 * @returns {object} Parsed credentials object with `routed` and `relayed` sections
 */
function readCredentials() {
  if (!fs.existsSync(CREDENTIALS_PATH)) {
    throw new Error(
      'E2E credentials not found. This usually means globalSetup failed.\n' +
      'Make sure E2E_API_KEY and E2E_API_SECRET environment variables are set.\n' +
      'Credentials file expected at: ' + CREDENTIALS_PATH
    );
  }
  return JSON.parse(fs.readFileSync(CREDENTIALS_PATH, 'utf8'));
}

/**
 * Returns routed session credentials.
 *
 * @returns {Promise<{apiKey: string, apiSecret: string, apiUrl: string, jsSdkUrl: string, sessionId: string, tokenApp: string, tokenBot: string, tokenBot2: string, tokenSubscriber: string, mediaMode: string}>}
 */
async function getCredentials() {
  const creds = readCredentials();
  return creds.routed;
}

/**
 * Returns relayed (P2P) session credentials.
 *
 * @returns {Promise<{apiKey: string, apiSecret: string, apiUrl: string, jsSdkUrl: string, sessionId: string, tokenApp: string, tokenBot: string, mediaMode: string}>}
 */
async function getRelayedCredentials() {
  const creds = readCredentials();
  return creds.relayed;
}

module.exports = { getCredentials, getRelayedCredentials };
