// swift-tools-version: 6.0
// Self-managed SPM manifest for the @vonage/client-sdk-video-react-native
// wrapper's iOS native sources. React Native 0.87's SPM autolinking discovers
// this file via findSelfManagedPackageDir (checked before RN's mixed-source
// rejection) and consumes the `ClientSdkVideoReactNative` product.
//
// IMPORTANT: This file must NOT contain the string
// "AUTO-GENERATED by scripts/generate-spm-autolinking.js" or RN will treat it
// as its own synth output and overwrite it.
//
// The wrapper is a mixed-language module. SPM forbids Swift + ObjC/C++ in one
// target, and the sources form a Swift<->ObjC cycle (the .mm TurboModule/Fabric
// glue depends on the Swift impls; the Swift impls depend on lightweight ObjC
// classes). We break the cycle with three targets:
//
//   OpentokReactNativeObjC   (ObjC, no C++)  — leaf ObjC classes/headers that
//                                              Swift consumes (emitter iface,
//                                              lightweight ComponentView UIView
//                                              decls, OTScreenCapture). Depends
//                                              on VonageClientSDKVideo (OpenTok).
//   OpentokReactNativeSwift  (Swift)         — the 7 `import OpenTok` Swift
//                                              files. Depends on the ObjC core
//                                              and VonageClientSDKVideo.
//   OpentokReactNative       (ObjC++)        — the 3 .mm TurboModule/Fabric
//                                              bridges. Depends on the Swift
//                                              target (for -Swift.h), the ObjC
//                                              core, and the React header
//                                              products. This is the product's
//                                              root target.
//
// NOTE on the React header dependencies below: they are declared as path-based
// package deps on the consuming app's generated `ReactNative` /
// `React-GeneratedCode` packages. The relative paths are the CANONICAL values
// RN's own autolinking computes (resolved from the `libs/<SwiftName>` symlink,
// an RN-0.87 invariant), so they are portable across consuming apps — see the
// detailed rationale on those two `.package(...)` lines. RN injects no ambient
// React header search path into self-managed targets, so they cannot be dropped.

import PackageDescription

// React Native header products consumed by all three targets. Mirrors the
// `headersDep` list in the generated React-GeneratedCode Package.swift:
// React/RN/deps headers from the ReactNative package, plus the per-app codegen
// headers (RNOpentokReactNativeSpec) from React-GeneratedCode's ReactAppHeaders.
let reactHeaderDeps: [Target.Dependency] = [
    .product(name: "ReactHeaders", package: "ReactNative"),
    .product(name: "ReactNativeHeaders", package: "ReactNative"),
    .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
    .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
]

let package = Package(
    name: "ClientSdkVideoReactNative",
    platforms: [.iOS(.v17)],
    products: [
        .library(
            name: "ClientSdkVideoReactNative",
            // No explicit `type:` -> SPM "automatic" linkage. Xcode links this
            // RN module into the app binary (which is what links React's
            // dynamic xcframeworks); an explicit `.dynamic` framework was tried
            // and rejected because it would have to resolve React symbols the
            // app owns. All three targets are exposed so the Swift impls and
            // the ObjC core object files are part of the product.
            targets: [
                "OpentokReactNative",
                "OpentokReactNativeSwift",
                "OpentokReactNativeObjC",
            ]
        ),
    ],
    dependencies: [
        // The Vonage Video Client SDK. Its `VonageClientSDKVideo` product
        // includes the `OpenTok` binaryTarget, so `import OpenTok` and
        // `#import <OpenTok/OpenTok.h>` resolve unchanged. Depend on the
        // product by SPM package identity ("vonage-video-client-sdk-swift"),
        // NOT the manifest name ("VonageClientSDKVideo").
        .package(
            url: "https://github.com/vonage/vonage-video-client-sdk-swift",
            exact: "2.35.1"
        ),

        // React Native header packages that `react-native spm` generates in the
        // CONSUMING APP's build/ dir. `ReactNative` vends the React / RN /
        // third-party-deps headers; `React-GeneratedCode` vends the per-app
        // codegen product `ReactAppHeaders` (which carries our
        // `RNOpentokReactNativeSpec` generated headers). RN injects NO ambient
        // header search path into a self-managed package's targets, so these
        // must be declared here as real package dependencies — they cannot be
        // dropped without losing `<RNOpentokReactNativeSpec/...>` and `<React/...>`.
        //
        // Path resolution — why these hops are correct AND portable (do NOT
        // "fix" them): RN references a self-managed library through a symlink at
        //   <app>/ios/build/generated/autolinking/libs/<SwiftName>
        // and SPM resolves a manifest's relative package paths from that SYMLINK
        // LOCATION (logically, without following the link back to node_modules).
        // From `.../libs/<SwiftName>/` the app's generated packages are always at
        //   ../../../../xcframeworks      -> <app>/ios/build/xcframeworks
        //   ../../../ios                  -> <app>/ios/build/generated/ios
        // This `libs/<name>` -> `build/{xcframeworks,generated/ios}` layout is an
        // invariant of RN 0.87's SPM autolinking (identical for every consuming
        // app), so these are the canonical values RN's own scaffolder computes —
        // not a monorepo-specific accident. Verified against a green build.
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "React-GeneratedCode", path: "../../../ios"),
    ],
    targets: [
        // 1. Leaf ObjC core — what the Swift target imports. No C++.
        .target(
            name: "OpentokReactNativeObjC",
            dependencies: [
                .product(name: "VonageClientSDKVideo", package: "vonage-video-client-sdk-swift"),
            ] + reactHeaderDeps,
            path: ".",
            sources: [
                "OTScreenCapture.m",
            ],
            publicHeadersPath: "include/OpentokReactNativeObjC"
        ),

        // 2. Swift sources (all `import OpenTok`, `import React`).
        .target(
            name: "OpentokReactNativeSwift",
            dependencies: [
                "OpentokReactNativeObjC",
                .product(name: "VonageClientSDKVideo", package: "vonage-video-client-sdk-swift"),
            ] + reactHeaderDeps,
            path: ".",
            sources: [
                "OpentokReactNative.swift",
                "OTRN.swift",
                "OTRNPublisherComponentView.swift",
                "OTRNSubscriberComponentView.swift",
                "OTCustomAudioDriver.swift",
                "Utils/Utils.swift",
                "Utils/EventUtils.swift",
            ],
            swiftSettings: [
                // The sources predate Swift 6 strict concurrency. Compile in
                // Swift 5 language mode to match the original CocoaPods build
                // (swift_version = "5.0") and avoid Sendable errors.
                .swiftLanguageMode(.v5),
            ]
        ),

        // 3. ObjC++ TurboModule/Fabric bridges — the product root target.
        .target(
            name: "OpentokReactNative",
            dependencies: [
                "OpentokReactNativeSwift",
                "OpentokReactNativeObjC",
            ] + reactHeaderDeps,
            path: ".",
            sources: [
                "OpentokReactNative.mm",
                "OTRNPublisherComponentView.mm",
                "OTRNSubscriberComponentView.mm",
            ],
            cxxSettings: [
                // Match the prebuilt React.framework NDEBUG-gated C++ ABI so the
                // Fabric ShadowNode/Props layout aligns (see React-GeneratedCode
                // Package.swift for the rationale).
                .define("DEBUG", .when(configuration: .debug)),
                .define("NDEBUG", .when(configuration: .release)),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
