# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReactNativeTesApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => true,
    :hermes_enabled => true
  )




  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for C++20 compilation issues with Xcode 26+
    # Affects pods like fmt, Yoga, and other C++ libraries
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Check if this is a C++ target using C++20
        if config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] == 'c++20' || 
           config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] == 'gnu++20'
          config.build_settings['GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO'] = 'NO'
          # Remove -Werror to prevent warnings from failing the build
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          
          # Add -Wno-error to override any -Werror flags
          # This is more reliable than trying to remove -Werror from all sources
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= '$(inherited)'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] += ' -Wno-error'
        end
      end
    end
  end
end
