/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.uimanager.ViewManagerWithGeneratedInterface;

public interface OTRNSubscriberManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setSessionId(T view, @Nullable String value);
  void setStreamId(T view, @Nullable String value);
  void setSubscribeToAudio(T view, boolean value);
  void setSubscribeToVideo(T view, boolean value);
  void setScaleBehavior(T view, @Nullable String value);
  void setSubscribeToCaptions(T view, boolean value);
  void setAudioVolume(T view, float value);
  void setPreferredFrameRate(T view, int value);
  void setPreferredResolution(T view, @Nullable String value);
}
