/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.uimanager.ViewManagerWithGeneratedInterface;

public interface OTRNPublisherManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setSessionId(T view, @Nullable String value);
  void setPublisherId(T view, @Nullable String value);
  void setPublishAudio(T view, boolean value);
  void setPublishVideo(T view, boolean value);
  void setPublishCaptions(T view, boolean value);
  void setAudioBitrate(T view, int value);
  void setPublisherAudioFallback(T view, boolean value);
  void setSubscriberAudioFallback(T view, boolean value);
  void setAudioTrack(T view, boolean value);
  void setCameraPosition(T view, @Nullable String value);
  void setCameraTorch(T view, boolean value);
  void setCameraZoomFactor(T view, float value);
  void setEnableDtx(T view, boolean value);
  void setFrameRate(T view, int value);
  void setName(T view, @Nullable String value);
  void setResolution(T view, @Nullable String value);
  void setScalableScreenshare(T view, boolean value);
  void setAllowAudioCaptureWhileMuted(T view, boolean value);
  void setAudioFallbackEnabled(T view, boolean value);
  void setVideoTrack(T view, boolean value);
  void setVideoSource(T view, @Nullable String value);
  void setVideoContentHint(T view, @Nullable String value);
  void setMaxVideoBitrate(T view, int value);
  void setVideoBitratePreset(T view, @Nullable String value);
  void setScaleBehavior(T view, @Nullable String value);
  void setPublishSenderStats(T view, boolean value);
  void setPreferredVideoCodecs(T view, @Nullable String value);
}
